### ISSUE TITLE
Information missing from anaconda web UI

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/cudatoolkit-feedstock#2]
Link to package: https://anaconda.org/conda-forge/cudatoolkit

It's missing `License`, `Development`, `Documentation`, and `Description` that should look like this: https://anaconda.org/nvidia/cudatoolkit

This will cause issues with NVIDIA legal if it's not resolved.

**Comment by isuruf** [comment]
I think that's because @jakirkham  moved the package to `test` label

**Comment by jakirkham** [comment]
It didn't have those fields before.

**Comment by jakirkham** [comment]
We can change the license URL, but we should also add that to the recipe as it doesn't appear to be there.

I don't see a way on the Anaconda.org web interface to edit the other fields. A little surprised it doesn't pick these up from the package since it [already includes them]( https://github.com/conda-forge/cudatoolkit-feedstock/blob/f4db45c7239555e8c8927f354556b09ec8779adc/recipe/meta.yaml#L73-L82 ).

**Comment by jakirkham** [comment]
> We can change the license URL, but we should also add that to the recipe as it doesn't appear to be there.

Have added PR ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/3 ) on this point. Appears the linter raised a few issues ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/3#issuecomment-708589954 ). Not sure how we want to address these.

**Comment by jakirkham** [comment]
Looking at [the `cudatoolkit` package in `cf-staging`]( https://anaconda.org/cf-staging/cudatoolkit ), it appears to actually show all of this metadata. I wonder if by copying the package over, Anaconda.org doesn't fill out these fields?

<img width="1792" alt="Screen Shot 2020-10-14 at 11 49 43 AM" src="https://user-images.githubusercontent.com/3019665/96032333-5e0cd980-0e13-11eb-84f0-20f7215191f3.png">

**Comment by scopatz** [comment]
`license_url` doesn't appear to be a [valid field](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html) but maybe I am missing something / it is undocumented?

**Comment by jakirkham** [comment]
It is [noted in the docs here]( https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html?highlight=license_url#info-about-json ) and [also Conda-Build notes it]( https://github.com/conda/conda-build/blob/ae08afba008a652715e3dfaad4fd51e8fc1b3105/conda_build/metadata.py#L520 ). IIUC this is what Anaconda.org uses to link out from the license field. That said, the documentation is pretty sparse here.

**Comment by jakirkham** [comment]
So one idea to get this to populate correctly would be to delete this package from Anaconda.org and manually upload the `cudatoolkit` file. This should hopefully trigger Anaconda.org to pull in this information from the package. My guess is the copying API we are using with Anaconda.org doesn't do that for some reason. Thoughts on this approach?

**Comment by isuruf** [comment]
Sounds good. Same happened for a recent package https://anaconda.org/conda-forge/redis

**Comment by jakirkham** [comment]
I manually edited the description and license URL in the short-term to make sure that matches. The other fields don't appear to be editable from the web UI.

If we are ok with deleting and reuploading the package, I can give that a try after the current meeting I'm in (~45mins).

**Comment by scopatz** [comment]
I am OK with that.  No one should have used it at this point

**Comment by jakirkham** [comment]
Ok so I downloaded the package locally. Deleted the package from `conda-forge` and then reuploaded the same package. As the `license_url` wasn't in the recent package, I went in and edited this manually. Have also added the `broken` label to the package per this suggestion ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/3#issuecomment-708596954 ). Here's a screenshot of how things look below (though one can also [visit Anaconda.org to see this as well]( https://anaconda.org/conda-forge/cudatoolkit )). By eye this seems to look right, but would be helpful if people double check 🙂

<img width="1792" alt="Screen Shot 2020-10-14 at 1 47 31 PM" src="https://user-images.githubusercontent.com/3019665/96043450-d1b6e280-0e23-11eb-9d51-7b1a376dbfcb.png">

**Comment by kkraus14** [comment]
Things LGTM now, thanks @jakirkham 😄

**Comment by jakirkham** [comment]
> Have also added the `broken` label to the package per this suggestion ( [#3 (comment)](https://github.com/conda-forge/cudatoolkit-feedstock/pull/3#issuecomment-708596954) ).

Seems labeling it `broken` wasn't quite sufficient for marking it as `broken` as it still comes up in CI ( https://github.com/conda-forge/ucx-split-feedstock/pull/80#issuecomment-708864031 ). Proposing we go through the `admin-requests` process ( https://github.com/conda-forge/admin-requests/pull/143 ). That should fix this until we have some time to build this out more fully.

**Comment by beckermr** [comment]
Yes @jakirkham. You have to go through admin-requests because we changed the process a while back. Broken packages are left on main but removed from the repodata. This removal process requires rebuilding the repodata patches. The admin-requests repo does this automatically.

**Comment by jakirkham** [comment]
Thanks Matt! That seems to have fixed things 😄

**Comment by leofang** [comment]
Thanks John for doing this! My impression is that manually uploading is the only way to update/fix the displayed information/metadata on Anaconda.org. Making changes in the recipe does not work unfortunately.

**Comment by jakirkham** [comment]
Ofc!

Yeah I suspect because we are using a particular API to copy packages between channels the metadata gets lost. Not sure if this is something we can fix in how we use [anaconda-client]( https://github.com/Anaconda-Platform/anaconda-client ) (or perhaps within anaconda-client) or if it's something about Anaconda.org itself.

**Comment by beckermr** [comment]
We use the client. Anaconda will have to fix it on their end.

**Comment by jakirkham** [comment]
I did a bit of digging into the source code yesterday. There may be a way to affect this through the Python API. That seems to be how they extract package metadata and push it to Anaconda.org when just uploading a packaging.

**Comment by beckermr** [comment]
Great! If you have a pr, the code for copies is in the webservices repo.

**Comment by jakirkham** [comment]
Didn't get that far. Was just getting a rough idea of what was happening. Likely requires more work.

My guess is it would be a PR to `anaconda-client`. We can of course dance around how they are doing things, but it seems better to just make sure that things are handled in the tool itself.

**Comment by beckermr** [comment]
Ahhh ok. So it is a fix on anacondas end.

**Comment by jakirkham** [comment]
Yeah sorry for being unclear. I don't think we are doing anything wrong.

More noting I don't think it is secret sauce in Anaconda.org. It's something we could make a PR to fix. `anaconda-client` seems like the right place to do that.

**Comment by jakirkham** [comment]
> Ok so I downloaded the package locally. Deleted the package from `conda-forge` and then reuploaded the same package. As the `license_url` wasn't in the recent package, I went in and edited this manually. Have also added the `broken` label to the package per this suggestion ( [#3 (comment)](https://github.com/conda-forge/cudatoolkit-feedstock/pull/3#issuecomment-708596954) ). Here's a screenshot of how things look below (though one can also [visit Anaconda.org to see this as well](https://anaconda.org/conda-forge/cudatoolkit)). By eye this seems to look right, but would be helpful if people double check 🙂

Had to do this again recently since we needed to delete old packages not complying with the EULA after PR ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/34 ) landed. Looks like the UI is back to rendering correctly. More details in comment ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/34#issuecomment-734049098 ). Also additional context is available in that thread. Here's a screenshot to show this is back to what we expect (though please let me know if anything is missing):

<img width="1792" alt="Screen Shot 2020-11-25 at 7 11 44 PM" src="https://user-images.githubusercontent.com/3019665/100304224-1d949580-2f53-11eb-9c67-ceb32e65fe89.png">

**Comment by jakirkham** [comment]
Well it looks like the package copied from `cf-staging` broke this unfortunately 😞 Unfortunately I don't have more time to look into this this week. We should revisit this next week. Going to reopen to track

<img width="1792" alt="Screen Shot 2020-11-25 at 7 29 50 PM" src="https://user-images.githubusercontent.com/3019665/100304879-99431200-2f54-11eb-8b68-e545d6d6ff41.png">

**Comment by jakirkham** [comment]
Trying one last idea. Deleting all of the `cudatoolkit` packages (including the ones under `test`) and reuploading the 9.2 package to start the `cudatoolkit` package fresh.

**Comment by jakirkham** [comment]
Ok that seems to work. Going to wait and see what happens once `cf-staging` packages get copied over.

**Comment by beckermr** [comment]
I suspect that will wreck it again.

**Comment by jakirkham** [comment]
I'm not sure. That is how we had things working initially. However if it doesn't work, I'll probably throw in towel (for today anyway).

**Comment by jakirkham** [comment]
Yep you're right. It's back to not rendering correctly 😞

**Comment by jakirkham** [comment]
Manually added the bits that I can through the Web UI.

Unfortunately am unable to add the development URL and doc URL. At least the license URL and description are correct.

**Comment by beckermr** [comment]
As long as this feedstock only has maintainers on core, we could allow direct uploads.

**Comment by beckermr** [comment]
We’d have to ask Mike and Leo to remove themselves. This is not a great option. 

We could change the webservices to do an upload job which downloads the artifact and pushes directly to the main channel instead of the copy

**Comment by jakirkham** [comment]
Yeah I'd prefer not to do that.

We at least have the right bits that pertain to the license (URL and description). The doc and dev URL are not easily fixable through the UI, but these seem less urgent.

The fact that copying does seem to override the metadata even after it is set correctly indicates we may be able to change `anaconda-client` to do this correctly when copying.

Anyways let's push pause here for now and we can revisit next week. Sound good? 🙂

**Comment by leofang** [comment]
If it helps I am happy to be removed. Haven't contributed much so far anyway, and I can still contribute even as a non-maintainer.

**Comment by jakirkham** [comment]
I don’t think that’s necessary Leo. In fact would prefer to keep you so I can get your feedback on things periodically 😉

Anyways let’s all spend some time with family and relax. I’m confident we will be able to find a good solution once we are fresh next week 🙂

**Comment by beckermr** [comment]
So I have been checking into this. The only thing the anaconda client does when copying a package is call the `copy` endpoint here: https://api.anaconda.org/docs#!/package/post_copy_package_owner_login_package_name_version_basename

As we tested above, this nukes the information in the web UI even if it is already set. 

Thus whatever is happening is happening on the anaconda backend and not in the client code we are calling. 

Our options are to 

1. Ask anaconda to fix this
2. Download the artifact from cf-staging and push it back up to conda-forge
3. Do a direct upload somehow.

**Comment by beckermr** [comment]
If anaconda does fix this so that a copy doesn't nuke the package info, this PR should make sure to copy the package info before uploading: https://github.com/conda-forge/conda-forge-webservices/pull/413

I'll leave it open for now in draft status.

**Comment by kkraus14** [comment]
Closing this issue as it's resolved.

**Comment by jakirkham** [comment]
Well the dev and doc URLs are still missing. Not sure how important that is to us. Haven't found a good way of fixing them unfortunately 😞

**Comment by jaimergp** [comment]
I think it might be fixed soon! See https://gitter.im/conda-forge/conda-forge.github.io?at=600af4fdcf8b827734494533

**Comment by kkraus14** [comment]
Will reopen, but the main thing I was worried about was losing the license info 😄

**Comment by jakirkham** [comment]
For sure, the license info is working correctly and can be changed more easily if needed. Just trying to be transparent about the outstanding issues 🙂

**Comment by jakirkham** [comment]
Looks like these were fixed recently! 😄 🎉

<img width="1792" alt="Screen Shot 2021-02-18 at 11 35 58 PM" src="https://user-images.githubusercontent.com/3019665/108472863-23440380-7242-11eb-9b59-644cae87f892.png">
