### ISSUE TITLE
can we distribute libcuinj64.so and libaccinj64.so?

### ISSUE THREAD

**Issue by isuruf** [conda-forge/cudatoolkit-feedstock#30]
They are not mentioned in https://docs.nvidia.com/cuda/archive/10.2/eula/index.html#cuda-toolkit-supplement-license-agreement

cc @kkraus14, @jakirkham

**Comment by kkraus14** [comment]
If it's not included in the EULA we should assume we're not allowed to distribute it. As far as I know `libcuinj` and `libaccinj` are used by profiling tools like `nvprof` and typically aren't used by any libraries.

Will follow up internally to double check on this though.

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/34 ) to drop these libraries.
