### ISSUE TITLE
`.lib`s missing on Windows

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cudatoolkit-feedstock#35]
Looking at the Windows binaries it appears the `.lib`s are not included. Only the `.dll`s are in `Library\bin`. Also `Library\lib` appears to be absent.

**Comment by jakirkham** [comment]
Should add I would assume this is an issue. Don't personally use Windows enough to say for sure.

FWIW they are noted as distributable under the EULA. So we could distribute them if they are indeed needed.

**Comment by jakirkham** [comment]
@jaimergp has this affected you or your users?

**Comment by isuruf** [comment]
This issue wouldn't show up if the version of `cudatoolkit` on the build machine is the same as the one in the `cudatoolkit` package. Otherwise it would show up

**Comment by jakirkham** [comment]
I see. So these won't actually be used when installing on a user's system. Is that right? So it doesn't matter if these are shipped.

So the only question here is whether we are doing a good job of aligning CUDA versions used with build tools on CI.

**Comment by jaimergp** [comment]
I will run some tests locally during the week and see if I can run into problems on purpose.

**Comment by jaimergp** [comment]
Update: OpenMM seems to work ok for simple tests and simulations. I haven't tried to do more advanced stuff like C++ plugins and so on, but those are very rare cases.

**Comment by jakirkham** [comment]
Thanks for the update. Ok sounds like we can safely ignore these for now. If they become relevant in the future, we can always revisit 🙂

**Comment by jakirkham** [comment]
Closing as it sounds like there is nothing further to do here
