### ISSUE TITLE
Support for CUDA 11.1

### ISSUE THREAD

**Issue by davidrpugh** [conda-forge/cudatoolkit-feedstock#36]
Thanks for the great work! What can I do to help get support for CUDA 11.1? Would be great help to all users of new RTC 30 series GPUs.

https://news.developer.nvidia.com/cuda-11-1-introduces-support-rtx-30-series/

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/cudatoolkit-feedstock/pull/26

**Comment by davidrpugh** [comment]
Thanks for the pointer! Looks like others are already working on this. Will go ahead and close.
