### ISSUE TITLE
How to add a new version

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/cudatoolkit-feedstock#38]
I will try to compile the instructions for adding a new version to the build matrix, since `cudatoolkit` is only one part of the CUDA ecosystem on conda-forge and it's not trivial. We can extend this as needed and pin the issue, move to the documentation or whatever you prefer.

1. Add the `cudatoolkit` packages in this feedstock.
2. Submit the version migration to [`conda-forge-pinning-feedstock`](https://github.com/conda-forge/conda-forge-pinning-feedstock). This will stay open during the following steps.
3. For Linux, add the corresponding Docker images at [`docker-images`](https://github.com/conda-forge/docker-images). Copy the migration file manually to `.ci_support/migrations`. This copy should _not_ specify a timestamp. Comment it out! Rerender.
4. For Windows, add the installer URLs and hashes in [`conda-forge-ci-setup`](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/install_cuda.bat). The manual migration must also be performed here. Rerender.
5. Create the new [`nvcc` ](https://github.com/conda-forge/nvcc-feedstock) packages for the new version. Again, manual migration must be added. Rerender.
6. After careful testing, consider merging the migration now so it can apply to all the downstream feedstocks.

> Note: CUDA 11 and above might need manual edits to make sure the corresponding YML files under `.ci_support` specify `cdt_name: cos7` and `zipped_keys: - [docker_image, cuda_compiler_version, cdt_name]`.

**Comment by jakirkham** [comment]
Thanks for putting this together Jaime! 😄

Should we start moving this kind of information to [the docs]( https://github.com/conda-forge/conda-forge.github.io/tree/master/src )? 🙂

**Comment by jaimergp** [comment]
That'd work too! I'll add to my list for December :)

**Comment by jaimergp** [comment]
Added as part of https://github.com/conda-forge/conda-forge.github.io/pull/1226
