### ISSUE TITLE
libcupti library missing from packages

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/cudatoolkit-feedstock#40]
In https://github.com/conda-forge/cudatoolkit-feedstock/pull/26 it was pointed out that there was warnings from missing the `libcupti` shared library:

```
WARNING (cudatoolkit,lib/libaccinj64.so.11.1.105): $RPATH/libcupti.so.11.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
2020-11-05T19:47:11.2526306Z .. is this binary repackaging?
```

We no longer ship the libraries that depended on `libcupti` so we no longer get this warning, but we're still not shipping the `libcupti` shared library and we should be.

I'm not sure of the state of the package on Windows.

**Comment by jakirkham** [comment]
We are not currently packaging this on Windows AFAICT. Looking at [this CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=242568&view=logs&j=2d03c380-16cc-53df-474d-81b5b5dc65ac&t=e2a03de1-3f34-5c48-570c-8a55081b5756 ) (with [raw log attached]( https://github.com/conda-forge/cudatoolkit-feedstock/files/5569731/win_64_major_minor_ver11.1_20201119.3.txt )), we can see the following libraries related to `cupti`. Do we just want the year versioned one or do we want the `nvperf_*` ones as well?

```
2020-11-19T19:54:16.3312406Z Extracting  cuda_cupti\cupti\extras\CUPTI\lib64\cupti64_2020.2.1.dll
2020-11-19T19:54:16.3312905Z Extracting  cuda_cupti\cupti\extras\CUPTI\lib64\nvperf_host.dll
2020-11-19T19:54:16.3313372Z Extracting  cuda_cupti\cupti\extras\CUPTI\lib64\nvperf_target.dll
```

**Comment by kkraus14** [comment]
> Do we just want the year versioned one or do we want the nvperf_* ones as well?

The `nvperf_*` libraries aren't included in the EULA so we probably shouldn't include them unless we find there's a reason to do so. It would be nice if there was a library that uses cupti that we could use for testing.

**Comment by jaimergp** [comment]
https://github.com/srvm/cupti_profiler relies on cupti and has one example included.
