### ISSUE TITLE
Issues uploading Windows packages

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cudatoolkit-feedstock#54]
Not entirely sure what the issue is here, but with Windows we have started to see issues uploading packages to Anaconda.org. Basically these jobs will take a really long time trying to perform the upload and eventually fail. Maybe this has to do with package size or some other limitation? Here's an [example run with this issue]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=272880&view=logs&j=533b006e-c27f-58a3-8df4-b5a79e785988 )

**Comment by jakirkham** [comment]
@chenghlee is this something you might be able to look into a little more? I'm wondering if Anaconda.org might be running into some issue. Thinking this as we are downloading the installer from NVIDIA without issues.

**Comment by chenghlee** [comment]
Our infrastructure team is looking at it; we been seeing issues with other channels as well.

**Comment by jaimergp** [comment]
We are hitting this again with the last builds.

**Comment by jakirkham** [comment]
Just to add here is [a recent CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=385214&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c ) from today running into this issue

**Comment by leofang** [comment]
I've been doing retries since last night and was just able to get everything uploaded.

**Comment by jakirkham** [comment]
Seeing this again with [the build for 11.7.0]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=508965&view=logs&j=b14d9056-66e9-58f5-fe70-f09b2dad5d2c&s=96ac2280-8cb4-5df5-99de-dd2da759617d ). Restarted CI

**Comment by leofang** [comment]
Let us close this issue since it's been a while.
