### ISSUE TITLE
Windows CUDA 11.2 CI issue

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cudatoolkit-feedstock#65]
Looks like Windows builds for CUDA 11.2 are no longer working. Snippet of the error and link to the log below.

```
By installing, you accept licenses for the packages.
[NuGet] The operation has timed out
cuda not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '11.2.2.46133'. It is possible that version
 does not exist for 'cuda' at the source specified.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=377828&view=logs&jobId=0c54b711-eda0-5451-8966-40b26dc1ddde&j=0c54b711-eda0-5451-8966-40b26dc1ddde&t=033ee222-fd3b-5f5f-8d4a-b56ae81e2bde

cc @jaimergp @leofang

**Comment by jaimergp** [comment]
I think we can bump the chocolatey version. It's only needed for the drivers, I think.
