### ISSUE TITLE
OSX package

### ISSUE THREAD

**Issue by hadim** [conda-forge/cudatoolkit-feedstock#79]
### Comment:

I am wondering if there is a specific reason to not build OSX packages here? Or whether this is simply a lack of time to put the effort in it?

Are people simply using `cudatoolkit` from the `anaconda` channel as fallback? (we are trying to minimize the number of channels we work with)

**Comment by leofang** [comment]
CUDA's Mac support is already killed for a few years. There's no way we can support macOS.

**Comment by ngam** [comment]
> CUDA's Mac support is already killed for a few years. There's no way we can support macOS.

@leofang I have a feeling Apple is gonna attach an A-series card to their yet-to-be-released Mac Pro 😆 🤣
