### ISSUE TITLE
Packaging other versions

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cudatoolkit-feedstock#8]
Opening this issue to discuss how we handle packaging other versions of `cudatoolkit`. Can see a few options...

1. Create other branches particularly for older versions (this is typically how we do things)
2. Use a build matrix of CUDA versions (this is how we [do things in the `nvcc` wrapper package]( https://github.com/conda-forge/nvcc-feedstock/blob/53bd9be01d52f874c2b303d1c883af1a99d8979d/recipe/meta.yaml#L13 ))
3. ?

1 is simple and follows the status quo. So is easy to do. The one downside is it requires a concerted effort to backport fixes to older `cudatoolkit` versions. Along these lines it is easy for people to forget to backport changes or even when trying to backport run into additional peculiarities in older versions that cause problems. That said, this is arguably a feature. CUDA versions that are not that important to the community don't take additional resources.

2 follows `nvcc` so naturally matches how we handle that case here. Also it makes sure that all CUDA versions get the same fix. However this requires more concerted effort to get all supported CUDA versions working initially. This can become more noticeable as the long tail of CUDA versions grows. On the flip side, this means when old versions becoming to painful/uninteresting to the community, they will be intentionally dropped (presenting a useful signal to downstream users).

There may be other ways we want to handle multiple versions. Other ideas would be very welcome. Hopefully this gets the thought process started 🙂

**Comment by scopatz** [comment]
FWIW, these take a long time to "build". I was planning on just starting in with option (1) tomorrow. The notion of a build matrix is nice, but I would like to see these moved off of the test label sooner rather than later.  I propose we go with (1) right now, and if there is interest, in parallel or in the future, someone can pursue (2).

**Comment by scopatz** [comment]
Thanks for bringing this up @jakirkham!

**Comment by scopatz** [comment]
yeah, to be clear, my notion here is to make adjustments to the recipe such that it is trivial to change between the versions that you want to build. I just don't want to kick off jobs for each version.  Hopefully this will make it easy to transition to building the full matrix

**Comment by jakirkham** [comment]
I'm just reflecting on why we made PRs to Anaconda's recipe in the past. It was usually something like a missing library, which we did want to add across the board, but we didn't have a good mechanism for managing that across versions.

Some relevant discussion here ( https://github.com/AnacondaRecipes/cudatoolkit-feedstock/issues/8 ).

**Comment by jakirkham** [comment]
Going to close out now that all the versions are up. If there is interest in having all versions in `master`, happy to discuss further. Otherwise we can stick with the status quo of a different branch for each version.

Thanks Anthony for all of your work here! 😄 🎉 🙏

**Comment by scopatz** [comment]
Yeah, of course! FWIW, I think the 9.2 branch should be merged to master, because this is branch that I would like people adjust when putting in PRs.

**Comment by jakirkham** [comment]
Reopening so we can track combining version branches together.

**Comment by jaimergp** [comment]
What's the suggested approach here? A multi-output recipe or a `conda_build_config.yaml` file listing all the requested `major_minor` versions?

**Comment by jakirkham** [comment]
That's what I had tried to do previously. Unfortunately it runs into some kind of parsing issue when re-rendering. So that's not quite enough. FWIW I shared the changes in PR ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/31 ) along with the error message encountered in case anyone has ideas.

**Comment by jakirkham** [comment]
Thanks to help from Isuru PR ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/31 ) now seems to work! Would be good to have some reviews when people have a moment 🙂
