### ISSUE TITLE
`CUDA_TOOLKIT_ROOT_DIR` not found

### ISSUE THREAD

**Issue by ma-sadeghi** [conda-forge/cudatoolkit-feedstock#82]
### Comment:

I was under the impression that installing `cudatoolkit` should also set relevant environment variables like `CUDA_TOOLKIT_ROOT_DIR`. Is there a way to automatically expose these env variables or I need to set them manually? Thanks!

**Comment by jaimergp** [comment]
It should be equivalent to `$CONDA_PREFIX`, at least for runtime libraries.

**Comment by ma-sadeghi** [comment]
@jaimergp Thank you so much for your reply. Quick question: does `cudatoolkit` provide dev tools like `nvcc`, etc.? I've tried `cudatoolkit-dev` for, but unfortunately it's outdated (11.4 or 11.3 IIRC). Thanks!

**Comment by jaimergp** [comment]
Due to Nvidia's EULA, we can only redistribute the runtime libraries.

If you want "the whole thing", you might be luckier with the [official nvidia channel](https://anaconda.org/nvidia)!

**Comment by ma-sadeghi** [comment]
Thank you! That's what I was looking for, but I was searching with the wrong keyword "cudatoolkit" (on NVIDIA's channel, it's "cuda-toolkit")!

**Comment by jakirkham** [comment]
We have a more complete set of packages starting with CUDA 12.0. Please see issue ( https://github.com/conda-forge/staged-recipes/issues/21382 ) for a full listing

More details about how these are being used in conda-forge can be seen in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1963 )
