### ISSUE TITLE
CUDA 12.0

### ISSUE THREAD

**Issue by raimis** [conda-forge/cudatoolkit-feedstock#87]
### Comment:

CUDA 12.0 has been released (https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-12-0-release-notes).

When can we expect a corresponding `cudatoolkit` package?

**Comment by leofang** [comment]
It's still WIP: https://github.com/conda-forge/staged-recipes/issues/21382

**Comment by jakirkham** [comment]
Yeah we are taking this opportunity to restructure how the packages work actually. Part of this is including the compiler as its own package. Another part of this is providing finer grain division of the libraries themselves so packages using them don't need to bring in as much stuff. This means it will take a bit longer. It also means we may not have a `cudatoolkit` package per-se as new packages supersede it.

**Comment by jakirkham** [comment]
This is out and packages are being rebuilt for CUDA 12. More details in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1963 )
