### ISSUE TITLE
Can this be used on WSL?

### ISSUE THREAD

**Issue by khayamgondal** [conda-forge/cudatoolkit-feedstock#88]
### Comment:

WSL requires Cuda only and no drivers. Does this version includes drivers as well? if so can there be a version without drivers for WSL?

**Comment by jakirkham** [comment]
AFAIK it works on WSL 2. Know a couple people who have tried, but have not tried myself.

This package only contains the libraries covered [here]( https://docs.nvidia.com/cuda/eula/index.html#attachment-a ).

It does not include the drivers. The user is on their own to install those.

**Comment by leofang** [comment]
We have several positive reports for WSL (not sure if it's 1 or 2, maybe 2). I think it should work just fine. You do need to set up the driver on the machine, same as using this package on Linux.
